import = ["/home/kevin/.config/alacritty/catppuccin/catppuccin-frappe.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[cursor.vi_mode_style]
shape = "Block"

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0000c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000-"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000\\"
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0000h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000k"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000x"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[shell]
args = ["-i", "-c", "tm; exec zsh"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0

[window.dimensions]
columns = 160
lines = 48

[window.padding]
x = 6
y = 6
